---
- name: Converge
  hosts: all
  vars:
    specify_app_protect_signatures_version: true
    specify_app_protect_threat_campaigns_version: true
    app_protect_signature_version_matrix:
      debian: =2022.12.29-1
      redhat: -2022.12.29
    app_protect_threat_campaigns_version_matrix:
      debian: =2023.01.11-1
      redhat: -2023.01.11
  tasks:
    - name: Set NGINX App Protect WAF signature version fact
      ansible.builtin.set_fact:
        nginx_app_protect_waf_signatures_version: "{{ app_protect_signature_version_matrix[ansible_facts['os_family'] | lower] }}{{ (ansible_facts['os_family'] | lower == 'debian') | ternary('~' ~ ansible_distribution_release, '') }}"
      when: specify_app_protect_signatures_version | bool

    - name: Set NGINX App Protect WAF threat campaigns version fact
      ansible.builtin.set_fact:
        nginx_app_protect_waf_threat_campaigns_version: "{{ app_protect_threat_campaigns_version_matrix[ansible_facts['os_family'] | lower] }}{{ (ansible_facts['os_family'] | lower == 'debian') | ternary('~' ~ ansible_distribution_release, '') }}"
      when: specify_app_protect_threat_campaigns_version | bool

    - name: Install NGINX App Protect WAF
      ansible.builtin.include_role:
        name: ansible-role-nginx-app-protect
      vars:
        nginx_app_protect_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
        nginx_app_protect_remove_license: false
        nginx_app_protect_waf_install_signatures: true
        nginx_app_protect_waf_install_threat_campaigns: true
