---
- name: Converge
  hosts: all
  vars:
    specify_app_protect_signatures_version: true
    specify_app_protect_threat_campaigns_version: true
    app_protect_signature_version_matrix:
      alpine: "=2021.01.20-r1"
      debian: "=2019.07.16-1"
      redhat: "-2019.07.16"
    app_protect_threat_campaigns_version_matrix:
      alpine: "=2021.01.03-r1"
      debian: "=2020.08.20-1"
      redhat: "-2020.08.20"
  tasks:
    - name: Set NGINX App Protect WAF signature version fact
      set_fact:
        nginx_app_protect_signatures_version: "{{ app_protect_signature_version_matrix[ansible_os_family | lower] }}{{ (ansible_os_family | lower == 'debian') | ternary('~' ~ ansible_distribution_release, '') }}"
      when: specify_app_protect_signatures_version| bool

    - name: Set NGINX App Protect WAF threat campaigns version fact
      set_fact:
        nginx_app_protect_threat_campaigns_version: "{{ app_protect_threat_campaigns_version_matrix[ansible_os_family | lower] }}{{ (ansible_os_family | lower == 'debian') | ternary('~' ~ ansible_distribution_release, '') }}"
      when: specify_app_protect_threat_campaigns_version| bool

    - name: Install NGINX App Protect WAF
      include_role:
        name: ansible-role-nginx-app-protect
      vars:
        nginx_app_protect_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
        nginx_app_protect_remove_license: false
        nginx_app_protect_install_signatures: true
        nginx_app_protect_install_threat_campaigns: true
        nginx_app_protect_configure: false
        nginx_app_protect_waf_state: present
