---
- name: Verify
  hosts: all
  vars:
    specify_app_protect_signatures_version: true
    specify_app_protect_threat_campaigns_version: true
    app_protect_signature_version_matrix:
      debian: "=2019.07.16-1"
      redhat: "-2019.07.16"
    app_protect_threat_campaigns_version_matrix:
      debian: "=2020.08.20-1"
      redhat: "-2020.08.20"
  tasks:
    - name: Check if NGINX Plus is installed
      ansible.builtin.package:
        name: nginx-plus
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX App Protect WAF is installed
      ansible.builtin.package:
        name: app-protect
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX App Protect WAF signatures is installed
      ansible.builtin.package:
        name: app-protect-attack-signatures
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX App Protect WAF threat campaigns is installed
      ansible.builtin.package:
        name: app-protect-threat-campaigns
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Check NGINX App Protect WAF version
      block:
        - name: Check installed software
          ansible.builtin.package_facts:
            manager: auto

        - name: Verify installed NAP signatures version matches requested version
          ansible.builtin.assert:
            that: "{{ (ansible_facts.packages['app-protect-attack-signatures'] | map(attribute='version') | first) == (app_protect_signature_version_matrix[ansible_os_family | lower] | regex_replace('^-|=','') + (ansible_os_family | lower == 'debian') | ternary('~' ~ ansible_distribution_release, '')) }}"

        - name: Verify installed NAP threat campaigns version matches requested version
          ansible.builtin.assert:
            that: "{{ (ansible_facts.packages['app-protect-threat-campaigns'] | map(attribute='version') | first) == (app_protect_threat_campaigns_version_matrix[ansible_os_family | lower] | regex_replace('^-|=','') + (ansible_os_family | lower == 'debian') | ternary('~' ~ ansible_distribution_release, '')) }}"
