---
- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect license
  blockinfile:
    path: /etc/apt/apt.conf.d/90nginx
    create: true
    block: |
      Acquire::https::plus-pkgs.nginx.com::Verify-Peer "true";
      Acquire::https::plus-pkgs.nginx.com::Verify-Host "true";
      Acquire::https::plus-pkgs.nginx.com::SslCert     "/etc/ssl/nginx/nginx-repo.crt";
      Acquire::https::plus-pkgs.nginx.com::SslKey      "/etc/ssl/nginx/nginx-repo.key";
    state: "{{ nginx_app_protect_license_status | default ('present') }}"
    mode: 0444

- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect security updates license
  blockinfile:
    path: /etc/apt/apt.conf.d/90app-protect-security-updates
    create: true
    block: |
      Acquire::https::app-protect-security-updates.nginx.com::Verify-Peer "true";
      Acquire::https::app-protect-security-updates.nginx.com::Verify-Host "true";
      Acquire::https::app-protect-security-updates.nginx.com::SslCert     "/etc/ssl/nginx/nginx-repo.crt";
      Acquire::https::app-protect-security-updates.nginx.com::SslKey      "/etc/ssl/nginx/nginx-repo.key";
    state: "{{ nginx_app_protect_license_status | default ('present') }}"
    mode: 0444
  when: nginx_app_protect_install_signatures | bool
        or nginx_app_protect_install_threat_campaigns | bool

- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect repository
  apt_repository:
    repo: "{{ nginx_app_protect_repository | default(nginx_app_protect_default_repository_debian) }}"
    filename: nginx-app-protect
    mode: 0644
    update_cache: false
    state: "{{ nginx_app_protect_license_status | default ('present') }}"

- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect security updates repository
  apt_repository:
    repo: "{{ nginx_app_protect_security_updates_repository | default(nginx_app_protect_security_updates_default_repository_debian) }}"
    filename: app-protect-security-updates
    mode: 0644
    update_cache: false
    state: "{{ nginx_app_protect_license_status | default ('present') }}"
  when: nginx_app_protect_install_signatures | bool
        or nginx_app_protect_install_threat_campaigns | bool

- name: (Debian/Ubuntu) Install NGINX App Protect
  apt:
    name: "app-protect"
    state: "{{ nginx_app_protect_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Debian/Ubuntu) Install NGINX App Protect signatures {{ nginx_app_protect_signatures_version is defined | ternary(nginx_app_protect_signatures_version, '') }}
  apt:
    name: "app-protect-attack-signatures{{ nginx_app_protect_signatures_version | default('') }}"
    state: "{{ nginx_app_protect_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - nginx_app_protect_install_signatures | bool
    - nginx_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Debian/Ubuntu) Install NGINX App Protect threat campaigns {{ nginx_app_protect_threat_campaigns_version is defined | ternary(nginx_app_protect_threat_campaigns_version, '') }}
  apt:
    name: "app-protect-threat-campaigns{{ nginx_app_protect_threat_campaigns_version | default('') }}"
    state: "{{ nginx_app_protect_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - nginx_app_protect_install_threat_campaigns | bool
    - nginx_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX
