---
- name: Get NGINX Plus version
  set_fact:
    nginx_plus_version: "{{ ansible_facts.packages['nginx-plus'] | map(attribute='version') | list | first | regex_search('^(\\d{1,3})') }}"
  when: "'nginx-plus' in ansible_facts.packages"

- name: Fail if existing NGINX Plus version preconditions fails
  assert:
    that: nginx_plus_version | int >= 19
    fail_msg: >
      "'nginx_plus_version' release version must be a minimum of 19 for App Protect.
      Actual: {{ (nginx_plus_version is defined) | ternary(nginx_plus_version, 'NONE') }}"
    success_msg: "'nginx_plus_version' is {{ (nginx_plus_version is defined) | ternary(nginx_plus_version, 'NONE') }}"
    quiet: true
  when: nginx_plus_version is defined

- name: Install NGINX App Protect
  include_tasks: "{{ role_path }}/tasks/install/install-{{ ansible_os_family | lower }}.yml"

- name: Install NGINX App Protect signatures ({{ nginx_app_protect_signatures_version is defined | ternary(nginx_app_protect_signatures_version, 'latest') }})
  package:
    name: "app-protect-attack-signatures{{ nginx_app_protect_signatures_version | default('') }}"
    state: "{{ nginx_app_protect_state }}"
  when:
    - nginx_app_protect_install_signatures | bool
    - nginx_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: Install NGINX App Protect threat campaigns ({{ nginx_app_protect_threat_campaigns_version is defined | ternary(nginx_app_protect_threat_campaigns_version, 'latest') }})
  package:
    name: "app-protect-threat-campaigns{{ nginx_app_protect_threat_campaigns_version | default('') }}"
    state: "{{ nginx_app_protect_state }}"
  when:
    - nginx_app_protect_install_threat_campaigns | bool
    - nginx_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: Modify NGINX Plus service
  block:
    - name: Create override for NGINX Plus service
      file:
        path: /etc/systemd/system/nginx.service.d
        state: directory
        mode: 0755

    - name: Increase timeout for NGINX Plus service
      template:
        src: nginx.service.override.conf.j2
        dest: /etc/systemd/system/nginx.service.d/override.conf
        owner: root
        group: root
        mode: 0644
      notify: (Handler - NGINX App Protect) Systemd daemon-reload
  when: nginx_app_protect_service_modify | bool
