---
- name: Get NGINX Plus version
  set_fact:
    nginx_plus_version: "{{ ansible_facts.packages['nginx-plus'] | map(attribute='version') | list | first | regex_search('^(\\d{1,3})') }}"
  when: "'nginx-plus' in ansible_facts.packages"

- name: Fail if NGINX Plus version preconditions fail
  assert:
    that: nginx_plus_version | int >= 19
    fail_msg: >
      "'nginx_plus_version' release version must be a minimum of 19 for App Protect.
      Actual: {{ (nginx_plus_version is defined) | ternary(nginx_plus_version, 'NONE') }}"
    success_msg: "'nginx_plus_version' is {{ (nginx_plus_version is defined) | ternary(nginx_plus_version, 'NONE') }}"
    quiet: true
  when: nginx_plus_version is defined

- name: Install latest NGINX App Protect signatures
  package:
    name: app-protect-attack-signatures
    state: "{{ nginx_app_protect_state }}"
  when: nginx_app_protect_install_signatures | bool
  notify: (Handler) Restart NGINX

- name: Install latest NGINX App Protect threat campaigns
  package:
    name: app-protect-threat-campaigns
    state: "{{ nginx_app_protect_state }}"
  when: nginx_app_protect_install_threat_campaigns | bool
  notify: (Handler) Restart NGINX
