---
- name: (CentOS/RHEL) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect repository
  yum_repository:
    name: nginx-app-protect
    baseurl: "{{ nginx_app_protect_repository | default(nginx_app_protect_default_repository_redhat) }}"
    description: NGINX App Protect repository
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: true
    gpgcheck: true
    state: "{{ nginx_app_protect_license_status | default ('present') }}"

- name: (CentOS/RHEL) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect security updates repository
  yum_repository:
    name: nginx-app-protect-security-updates
    baseurl: "{{ nginx_app_protect_repository | default(nginx_app_protect_security_updates_default_repository_redhat) }}"
    description: NGINX App Protect security updates repository
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: true
    gpgcheck: true
    state: "{{ nginx_app_protect_license_status | default ('present') }}"

- name: (CentOS/RHEL) Install NGINX App Protect
  yum:
    name: "app-protect{{ nginx_app_protect_version | default('') }}"
    state: "{{ nginx_app_protect_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX
