---
- name: Set NGINX App Protect license state
  set_fact:
    nginx_app_protect_license_status: absent

- name: Delete repository data
  include_tasks: "{{ role_path }}/tasks/install/install-{{ ansible_facts['os_family'] | lower }}.yml"

- name: Delete NGINX App Protect license
  file:
    path: /etc/ssl/nginx
    state: absent
