---
driver:
  name: docker
lint: |
  set -e
  ansible-lint --force-color
platforms: # Ubuntu bionic results in a segmentation fault error as of Ansible core 2.13
  - name: centos-7
    image: centos:7
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: debian-bullseye
    image: debian:bullseye-slim
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: rhel-7
    image: registry.access.redhat.com/ubi7/ubi:7.9
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: rhel-8
    image: registry.access.redhat.com/ubi8/ubi:8.5
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: ubuntu-focal
    image: ubuntu:focal
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
