---
- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create ephemeral license certificate file from b64 decoded env var
      ansible.builtin.copy:
        content: "{{ lookup('env', 'NGINX_CRT') | b64decode }}" # noqa template-instead-of-copy
        dest: ../../files/license/nginx-repo.crt
        force: false
        mode: 0444

    - name: Create ephemeral license key file from b64 decoded env var
      ansible.builtin.copy:
        content: "{{ lookup('env', 'NGINX_KEY') | b64decode }}" # noqa template-instead-of-copy
        dest: ../../files/license/nginx-repo.key
        force: false
        mode: 0444

- name: Install NGINX App Protect WAF and DoS
  hosts: all
  vars:
    rhel_subscription: false
  pre_tasks:
    - name: (RHEL) Check if there is a valid RHEL subscription
      ansible.builtin.set_fact:
        rhel_subscription: true
      when:
        - lookup('env', 'RHEL_USERNAME') | length > 0
        - lookup('env', 'RHEL_PASSWORD') | length > 0

    - name: (RHEL) Register system into RHEL subscription manager
      community.general.redhat_subscription:
        username: "{{ lookup('env', 'RHEL_USERNAME') }}"
        password: "{{ lookup('env', 'RHEL_PASSWORD') }}"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - rhel_subscription| bool
  tasks:
    - name: Install NGINX App Protect WAF
      ansible.builtin.include_role:
        name: ansible-role-nginx-app-protect
      vars:
        nginx_app_protect_use_rhel_subscription_repos: "{{ rhel_subscription }}"
        nginx_app_protect_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
        nginx_app_protect_waf_enable: true
        nginx_app_protect_waf_install_signatures: true
        nginx_app_protect_waf_install_threat_campaigns: true
        nginx_app_protect_dos_enable: true
  post_tasks:
    - name: (RHEL) Unregister system from RHEL subscription manager
      community.general.redhat_subscription:
        state: absent
      when:
        - ansible_facts['distribution'] == "RedHat"
        - rhel_subscription | bool
