---
- name: (CentOS/RHEL) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  yum_repository:
    name: nginx-plus
    baseurl: "{{ nginx_plus_repository | default(nginx_plus_default_repository_redhat) }}"
    description: NGINX Plus repository
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: true
    gpgcheck: true
    state: "{{ nginx_app_protect_license_status | default ('present') }}"

- name: (CentOS/RHEL) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect DoS repository
  yum_repository:
    name: nginx-app-protect-dos
    baseurl: "{{ nginx_app_protect_dos_repository | default(nginx_app_protect_dos_default_repository_redhat) }}"
    description: NGINX App Protect repository
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: true
    gpgcheck: true
    state: "{{ nginx_app_protect_license_status | default ('present') }}"

- name: (CentOS/RHEL) Install NGINX App Protect DoS
  yum:
    name: "app-protect-dos"
    state: "{{ nginx_app_protect_dos_state }}"
    update_cache: true
    allow_downgrade: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX
