---
- name: (CentOS/RHEL) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  ansible.builtin.yum_repository:
    name: nginx-plus
    description: NGINX Plus repository
    baseurl: "{{ nginx_plus_repository | default(nginx_plus_default_repository_redhat) }}"
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: true
    gpgcheck: true
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_dos_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0644
  when: nginx_app_protect_dos_manage_repo | bool

- name: (CentOS/RHEL) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect DoS repository
  ansible.builtin.yum_repository:
    name: nginx-app-protect-dos
    description: NGINX App Protect DoS repository
    baseurl: "{{ nginx_app_protect_dos_repository | default(nginx_app_protect_dos_default_repository_redhat) }}"
    sslclientcert: /etc/ssl/nginx/nginx-repo.crt
    sslclientkey: /etc/ssl/nginx/nginx-repo.key
    enabled: true
    gpgcheck: true
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_dos_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0644
  when: nginx_app_protect_dos_manage_repo | bool

- name: (CentOS/RHEL) Force Yum cache refresh
  ansible.builtin.command: yum clean metadata
  changed_when: false

- name: (CentOS/RHEL) {{ nginx_app_protect_dos_setup | capitalize }} NGINX App Protect DoS
  ansible.builtin.yum:
    name: app-protect-dos{{ (nginx_app_protect_dos_state == 'absent') | ternary(',nginx-plus-module-appprotectdos', '') }}
    state: "{{ nginx_app_protect_dos_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX
