---
driver:
  name: docker
platforms:
  - name: alpine-3.22
    image: alpine:3.22
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: debian-bullseye
    image: debian:bullseye-slim
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: debian-bookworm
    image: debian:bookworm-slim
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: ubuntu-jammy
    image: ubuntu:jammy
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: ubuntu-noble
    image: ubuntu:noble
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    cleanup: ../common/cleanup.yml
  env:
    ANSIBLE_ROLES_PATH: ~/.cache/molecule/ansible-role-nginx/${MOLECULE_SCENARIO_NAME}/roles:${MOLECULE_PROJECT_DIRECTORY}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
