---
- name: Copy NGINX App Protect security policy files
  block:
    - name: Ensure NGINX App Protect security policy directories exist
      file:
        path: "{{ item.dest | default('/etc/app_protect/conf') | dirname }}"
        state: directory
        mode: 0755
      loop: "{{ nginx_app_protect_security_policy_file }}"

    - name: Copy NGINX App Protect security policy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest | default('/etc/app_protect/conf') }}"
        backup: true
        mode: 0644
      loop: "{{ nginx_app_protect_security_policy_file }}"
  when: nginx_app_protect_security_policy_file_enable | bool

- name: Copy NGINX App Protect log policy files
  block:
    - name: Ensure NGINX App Protect log policy directories exist
      file:
        path: "{{ item.dest | default('/etc/app_protect/conf') | dirname }}"
        state: directory
        mode: 0755
      loop: "{{ nginx_app_protect_log_policy_file }}"

    - name: Copy NGINX App Protect log policy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest | default('/etc/app_protect/conf') }}"
        backup: true
        mode: 0644
      loop: "{{ nginx_app_protect_log_policy_file }}"
  when: nginx_app_protect_log_policy_file_enable  | bool
