---
- name: Converge
  hosts: all
  tasks:
    - name: Install NGINX App Protect
      include_role:
        name: ansible-role-nginx-app-protect
      vars:
        nginx_app_protect_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
        nginx_app_protect_remove_license: false
        nginx_app_protect_install_signatures: true
        nginx_app_protect_install_threat_campaigns: true
        nginx_app_protect_configure: true
        nginx_app_protect_security_policy_template_enable: true
        nginx_app_protect_security_policy_enforcement_mode: blocking
        nginx_app_protect_log_policy_template_enable: true
        nginx_app_protect_log_policy_filter_request_type: all
        nginx_app_protect_conf_template_enable: false
