---
driver:
  name: docker
lint: |
  set -e
  ansible-lint --force-color
platforms:
  - name: amazonlinux-2
    image: amazonlinux:2
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: centos-7
    image: centos:7
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: debian-bullseye
    image: debian:bullseye-slim
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: oraclelinux-8
    image: oraclelinux:8
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: rhel-7
    image: registry.access.redhat.com/ubi7:7.9
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: rhel-8
    image: redhat/ubi8:8.7
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: ubuntu-bionic
    image: ubuntu:bionic
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: ubuntu-focal
    image: ubuntu:focal
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    converge: converge.yml
    verify: verify.yml
    cleanup: ../common/cleanup.yml
