---
- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create ephemeral license certificate file from b64 decoded env var
      copy:
        content: "{{ lookup('env','NGINX_CRT') | b64decode }}"
        dest: ../../files/license/nginx-repo.crt
        force: false
        mode: 0444

    - name: Create ephemeral license key file from b64 decoded env var
      copy:
        content: "{{ lookup('env','NGINX_KEY') | b64decode }}"
        dest: ../../files/license/nginx-repo.key
        force: false
        mode: 0444

- name: Install NGINX Plus R24 to avoid dependency issues
  hosts: all
  tasks:
    - name: Set repo if Alpine
      set_fact:
        version: "=24-r2"
      when: ansible_facts['os_family'] == "Alpine"
    - name: Set repo if Debian
      set_fact:
        version: "=24-2~{{ ansible_facts['distribution_release'] }}"
      when: ansible_facts['os_family'] == "Debian"
    - name: Set repo if Red Hat
      set_fact:
        version: "-24-2.{{ (ansible_facts['distribution']=='Amazon') | ternary('amzn2', ('el' + ansible_facts['distribution_major_version'] | string)) }}.ngx"
      when: ansible_facts['os_family'] == "RedHat"
    - name: Install NGINX Plus R24 to avoid dependency issues
      include_role:
        name: nginxinc.nginx
      vars:
        nginx_type: plus
        nginx_version: "{{ version }}"
        nginx_license:
          certificate: ../../files/license/nginx-repo.crt
          key: ../../files/license/nginx-repo.key
