---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      package:
        name: nginx-plus
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX App Protect is installed
      package:
        name: app-protect
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX App Protect Signatures is installed
      package:
        name: app-protect-attack-signatures
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX App Protect Threat Campaigns is installed
      package:
        name: app-protect-threat-campaigns
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Check that the security policy exists
      stat:
        path: /etc/nginx/app-protect-security-policy.json
      register: stat_result
      failed_when: not stat_result.stat.exists

    - name: Check that the log policy exists
      stat:
        path: /etc/nginx/app-protect-log-policy.json
      register: stat_result
      failed_when: not stat_result.stat.exists
