---
- name: Debug ansible_distribution
  debug:
    msg: "ansible_distribution {{ ansible_distribution }}"
    verbosity: 2

- name: Install Debian and Ubuntu prerequisites
  include_tasks: setup-debian.yml
  when: ansible_os_family == "Debian"

- name: Install CentOS prerequisites
  include_tasks: setup-centos.yml
  when: ansible_distribution == "CentOS"

- name: Install Red Hat prerequisites
  include_tasks: setup-redhat.yml
  when: ansible_distribution == "RedHat"
