---
- name: Debug Ansible distribution
  debug:
    msg: "ansible_distribution {{ ansible_facts['distribution'] }}"
    verbosity: 2

- name: (Debian/Ubuntu) Install dependencies
  include_tasks: setup-debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: (CentOS) Install dependencies
  include_tasks: setup-centos.yml
  when: ansible_facts['distribution'] == "CentOS"

- name: (RHEL) Install dependencies
  include_tasks: setup-redhat.yml
  when: ansible_facts['distribution'] == "RedHat"
