---
- name: (Debian/Ubuntu) Install dependencies
  apt:
    name: "{{ nginx_app_protect_debian_dependencies }}"
    update_cache: true
  when: ansible_os_family == "Debian"

- name: (CentOS) Install dependencies
  yum:
    name: "{{ nginx_app_protect_centos_dependencies }}"
  when: ansible_distribution == "CentOS"

- name: (RHEL) Install dependencies
  block:
    - name: (RHEL) Install packages
      yum:
        name: "{{ nginx_app_protect_rhel_dependencies }}"

    - name: (RHEL) Set up RHEL repository
      yum_repository:
        name: CentOS-7
        baseurl: "http://ftp.heanet.ie/pub/centos/{{ ansible_distribution_major_version }}/os/$basearch/"
        description: NGINX App Protect dependencies
        enabled: true
        gpgcheck: true
        gpgkey: "http://ftp.heanet.ie/pub/centos/{{ ansible_distribution_major_version }}/os/$basearch/\
                RPM-GPG-KEY-CentOS-{{ ansible_distribution_major_version }}"
        state: "{{ nginx_app_protect_license_status | default ('present') }}"
      when: not nginx_app_protect_use_rhel_subscription_repos | bool

    - name: (RHEL) Install dependencies from your RHEL subscription
      yum:
        name:
          - rhel-7-server-optional-rpms
          - rhel-7-server-rpms
      when: nginx_app_protect_use_rhel_subscription_repos | bool
  when: ansible_distribution == "RedHat"
