---
- name: (RHEL) Install dependencies
  yum:
    name: ca-certificates

- name: (RHEL) Install epel dependencies
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

- name: (RHEL) Set up RHEL repository
  yum_repository:
    name: CentOS-7
    baseurl: "http://ftp.heanet.ie/pub/centos/{{ ansible_facts['distribution_major_version'] }}/os/$basearch/"
    description: NGINX App Protect dependencies
    enabled: true
    gpgcheck: true
    gpgkey: "http://ftp.heanet.ie/pub/centos/{{ ansible_facts['distribution_major_version'] }}/os/$basearch/\
            RPM-GPG-KEY-CentOS-{{ ansible_facts['distribution_major_version'] }}"
    state: "{{ nginx_app_protect_license_status | default ('present') }}"
  when: not nginx_app_protect_use_rhel_subscription_repos | bool

- name: (RHEL) Install dependencies from your RHEL subscription
  yum:
    name:
      - rhel-7-server-optional-rpms
      - rhel-7-server-rpms
  when: nginx_app_protect_use_rhel_subscription_repos | bool
