---
driver:
  name: docker
platforms:
  - name: debian-bullseye
    image: debian:bullseye-slim
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
  - name: rhel-8
    image: redhat/ubi8:8.7
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: ubuntu-focal
    image: ubuntu:focal
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    converge: converge.yml
    verify: verify.yml
    cleanup: ../common/cleanup.yml
