---
- name: (WAF) Check whether you are using a supported NGINX App Protect WAF distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution | lower in nginx_app_protect_waf_linux_families.keys() | list
      - ansible_distribution_version | regex_search('\\d+\\.?\\d*') in nginx_app_protect_waf_linux_families[ansible_distribution | lower]
    success_msg: Your distribution, {{ ansible_distribution }} {{ ansible_distribution_version }}, is supported by NGINX App Protect WAF
    fail_msg: Your distribution, {{ ansible_distribution }} {{ ansible_distribution_version }}, is not supported by NGINX App Protect WAF
  when:
    - nginx_app_protect_waf_enable | bool
    - nginx_app_protect_waf_state != "absent"
  ignore_errors: true # noqa ignore-errors

- name: (DoS) Check whether you are using a supported NGINX App Protect DoS distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution | lower in nginx_app_protect_dos_linux_families.keys() | list
      - ansible_distribution_version | regex_search('\\d+\\.?\\d*') in nginx_app_protect_dos_linux_families[ansible_distribution | lower]
    success_msg: Your distribution, {{ ansible_distribution }} {{ ansible_distribution_version }}, is supported by NGINX App Protect DoS
    fail_msg: Your distribution, {{ ansible_distribution }} {{ ansible_distribution_version }}, is not supported by NGINX App Protect DoS
  when:
    - nginx_app_protect_dos_enable | bool
    - nginx_app_protect_dos_state != "absent"
  ignore_errors: true # noqa ignore-errors

- name: Abort if installing NGINX App Protect on RHEL >7 without subscription details
  ansible.builtin.fail:
    msg: NGINX App Protect cannot be installed on {{ ansible_distribution }} {{ ansible_distribution_version }} without setting the 'nginx_app_protect_use_rhel_subscription_repos' variable
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_version is version('7', '>')
    - not nginx_app_protect_use_rhel_subscription_repos | bool
