---
- name: Converge
  hosts: nap
  tasks:
    - name: Install NGINX App Protect WAF
      include_role:
        name: ansible-role-nginx-app-protect
      vars:
        nginx_app_protect_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
        nginx_app_protect_remove_license: false
        nginx_app_protect_install_signatures: true
        nginx_app_protect_install_threat_campaigns: true
        nginx_app_protect_configure: true
        nginx_app_protect_timeout: 180
