---
dependency:
  name: galaxy
  options:
    role-file: molecule/advanced/requirements.yml
driver:
  name: docker
platforms:
  - name: test-workload
    image: nginxdemos/hello
    platform: x86_64
    privileged: true
    groups:
      - workload
    networks:
      - name: molecule-test
  - name: ubuntu-focal
    image: ubuntu:focal
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    groups:
      - nap
    networks:
      - name: molecule-test
provisioner:
  name: ansible
  config_options:
    defaults:
      no_target_syslog: true
  log: false
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
