---
dependency:
  name: galaxy
  options:
    role-file: molecule/advanced/requirements.yml
driver:
  name: docker
lint: |
  set -e
  ansible-lint --force-color
platforms:
  - name: test-workload
    image: nginxdemos/hello
    platform: amd64
    privileged: true
    groups:
      - workload
    networks:
      - name: molecule-test
  - name: centos-7
    image: centos:7
    dockerfile: ../common/Dockerfile.j2
    platform: amd64
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    groups:
      - nap
    networks:
      - name: molecule-test
  - name: debian-buster
    image: debian:buster-slim
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    groups:
      - nap
    networks:
      - name: molecule-test
  - name: ubuntu-bionic
    image: ubuntu:bionic
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    groups:
      - nap
    networks:
      - name: molecule-test
  - name: ubuntu-focal
    image: ubuntu:focal
    platform: amd64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    groups:
      - nap
    networks:
      - name: molecule-test
provisioner:
  name: ansible
  config_options:
    defaults:
      no_target_syslog: true
  log: false
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
