---
- name: (Alpine Linux) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ nginx_plus_repository | default(nginx_plus_default_repository_alpine) }}"
    state: "{{ nginx_app_protect_license_status | default ('present') }}"
  when: nginx_app_protect_manage_repo | bool

- name: (Alpine Linux) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect WAF repository
  lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ nginx_app_protect_repository | default(nginx_app_protect_default_repository_alpine) }}"
    state: "{{ nginx_app_protect_license_status | default ('present') }}"
  when: nginx_app_protect_manage_repo | bool

- name: (Alpine Linux) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect WAF security updates repository
  lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ nginx_app_protect_security_updates_repository | default(nginx_app_protect_security_updates_default_repository_alpine) }}"
    state: "{{ nginx_app_protect_license_status | default ('present') }}"
  when:
    - (nginx_app_protect_install_signatures | bool) or (nginx_app_protect_install_threat_campaigns | bool)
    - nginx_app_protect_manage_repo | bool

- name: (Alpine Linux) Install NGINX App Protect
  apk:
    name: "app-protect"
    state: "{{ nginx_app_protect_waf_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Alpine Linux) Install NGINX App Protect WAF signatures {{ nginx_app_protect_signatures_version is defined | ternary(nginx_app_protect_signatures_version, '') }}
  apk:
    name: "app-protect-attack-signatures{{ nginx_app_protect_signatures_version | default('') }}"
    state: "{{ nginx_app_protect_waf_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - nginx_app_protect_install_signatures | bool
    - nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Alpine Linux) Install NGINX App Protect WAF threat campaigns {{ nginx_app_protect_threat_campaigns_version is defined | ternary(nginx_app_protect_threat_campaigns_version, '') }}
  apk:
    name: "app-protect-threat-campaigns{{ nginx_app_protect_threat_campaigns_version | default('') }}"
    state: "{{ nginx_app_protect_waf_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - nginx_app_protect_install_threat_campaigns | bool
    - nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX
