---
- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus license verification
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/90nginx
    create: true
    block: |
      Acquire::https::{{ (nginx_plus_repository | default(nginx_plus_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::Verify-Peer "true";
      Acquire::https::{{ (nginx_plus_repository | default(nginx_plus_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::Verify-Host "true";
      Acquire::https::{{ (nginx_plus_repository | default(nginx_plus_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::SslCert     "/etc/ssl/nginx/nginx-repo.crt";
      Acquire::https::{{ (nginx_plus_repository | default(nginx_plus_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::SslKey      "/etc/ssl/nginx/nginx-repo.key";
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0444

- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect WAF license verification
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/90app-protect
    create: true
    block: |
      Acquire::https::{{ (nginx_app_protect_waf_repository | default(nginx_app_protect_waf_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::Verify-Peer "true";
      Acquire::https::{{ (nginx_app_protect_waf_repository | default(nginx_app_protect_waf_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::Verify-Host "true";
      Acquire::https::{{ (nginx_app_protect_waf_repository | default(nginx_app_protect_waf_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::SslCert     "/etc/ssl/nginx/nginx-repo.crt";
      Acquire::https::{{ (nginx_app_protect_waf_repository | default(nginx_app_protect_waf_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::SslKey      "/etc/ssl/nginx/nginx-repo.key";
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0444

- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect WAF security updates license verification
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/90app-protect-security-updates
    create: true
    block: |
      Acquire::https::app-protect-security-updates.nginx.com::Verify-Peer "true";
      Acquire::https::app-protect-security-updates.nginx.com::Verify-Host "true";
      Acquire::https::app-protect-security-updates.nginx.com::SslCert     "/etc/ssl/nginx/nginx-repo.crt";
      Acquire::https::app-protect-security-updates.nginx.com::SslKey      "/etc/ssl/nginx/nginx-repo.key";
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0444
  when: nginx_app_protect_waf_install_signatures | bool
        or nginx_app_protect_waf_install_threat_campaigns | bool

- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  ansible.builtin.apt_repository:
    filename: nginx-plus
    repo: "{{ nginx_plus_repository | default(nginx_plus_default_repository_debian) }}"
    update_cache: false
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0644
  when: nginx_app_protect_waf_manage_repo | bool

- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect WAF repository
  ansible.builtin.apt_repository:
    filename: nginx-app-protect
    repo: "{{ nginx_app_protect_waf_repository | default(nginx_app_protect_waf_default_repository_debian) }}"
    update_cache: false
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0644
  when: nginx_app_protect_waf_manage_repo | bool

- name: (Debian/Ubuntu) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect WAF security updates repository
  ansible.builtin.apt_repository:
    filename: app-protect-security-updates
    repo: "{{ nginx_app_protect_waf_security_updates_repository | default(nginx_app_protect_waf_security_updates_default_repository_debian) }}"
    update_cache: false
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: 0644
  when:
    - (nginx_app_protect_waf_install_signatures | bool) or (nginx_app_protect_waf_install_threat_campaigns | bool)
    - nginx_app_protect_waf_manage_repo | bool

- name: (Debian/Ubuntu) {{ nginx_app_protect_waf_setup | capitalize }} NGINX App Protect WAF
  ansible.builtin.apt:
    name: app-protect{{ (nginx_app_protect_waf_state == 'absent') | ternary(',app-protect-compiler,app-protect-engine,app-protect-plugin,nginx-plus-module-appprotect', '') }}
    state: "{{ nginx_app_protect_waf_state }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Debian/Ubuntu) {{ nginx_app_protect_waf_setup | capitalize }} NGINX App Protect WAF signatures {{ nginx_app_protect_waf_signatures_version is defined | ternary(nginx_app_protect_waf_signatures_version, '') }}
  ansible.builtin.apt:
    name: app-protect-attack-signatures{{ nginx_app_protect_waf_signatures_version | default('') }}
    state: "{{ nginx_app_protect_waf_state }}"
    update_cache: true
    allow_downgrade: "{{ omit if ansible_version.full is version('2.12', '<') else true }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - nginx_app_protect_waf_install_signatures | bool
    - nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Debian/Ubuntu) {{ nginx_app_protect_waf_setup | capitalize }} NGINX App Protect WAF threat campaigns {{ nginx_app_protect_waf_threat_campaigns_version is defined | ternary(nginx_app_protect_waf_threat_campaigns_version, '') }}
  ansible.builtin.apt:
    name: app-protect-threat-campaigns{{ nginx_app_protect_waf_threat_campaigns_version | default('') }}
    state: "{{ nginx_app_protect_waf_state }}"
    update_cache: true
    allow_downgrade: "{{ omit if ansible_version.full is version('2.12', '<') else true }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - nginx_app_protect_waf_install_threat_campaigns | bool
    - nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX
