---
- name: (Alpine Linux) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX Plus repository
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ nginx_plus_repository | default(nginx_plus_default_repository_alpine) }}"
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
  when: nginx_app_protect_waf_manage_repo | bool

- name: (Alpine Linux) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect WAF repository
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ nginx_app_protect_waf_repository | default(nginx_app_protect_waf_default_repository_alpine) }}"
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
  when: nginx_app_protect_waf_manage_repo | bool

- name: (Alpine Linux) {{ nginx_app_protect_license_status is defined | ternary('Remove', 'Configure') }} NGINX App Protect WAF security updates repository
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: "{{ nginx_app_protect_waf_security_updates_repository | default(nginx_app_protect_waf_security_updates_default_repository_alpine) }}"
    state: "{{ nginx_app_protect_license_status | default((nginx_app_protect_waf_setup == 'uninstall') | ternary('absent', 'present')) }}"
  when: nginx_app_protect_waf_manage_repo | bool

- name: (Alpine Linux) {{ nginx_app_protect_waf_setup | capitalize }} NGINX Plus
  community.general.apk:
    name: nginx-plus
    repository: "{{ nginx_plus_repository | default(nginx_plus_default_repository_alpine) }}"
    state: "{{ nginx_app_protect_waf_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Alpine Linux) {{ nginx_app_protect_waf_setup | capitalize }} NGINX App Protect WAF
  community.general.apk:
    name: app-protect
    state: "{{ nginx_app_protect_waf_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Alpine Linux) {{ nginx_app_protect_waf_setup | capitalize }} NGINX App Protect WAF signatures {{ nginx_app_protect_waf_signatures_version is defined | ternary(nginx_app_protect_signatures_version, '') }}
  community.general.apk:
    name: app-protect-attack-signatures{{ nginx_app_protect_waf_signatures_version | default('') }}
    state: "{{ nginx_app_protect_waf_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX

- name: (Alpine Linux) {{ nginx_app_protect_waf_setup | capitalize }} NGINX App Protect WAF threat campaigns {{ nginx_app_protect_waf_signatures_version is defined | ternary(nginx_app_protect_signatures_version, '') }}
  community.general.apk:
    name: app-protect-threat-campaigns{{ nginx_app_protect_waf_threat_campaigns_version | default('') }}
    state: "{{ nginx_app_protect_waf_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: nginx_app_protect_license_status is not defined
  notify: (Handler - NGINX App Protect) Run NGINX
