---
name: Ansible Galaxy import
on:
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  galaxy:
    name: Galaxy
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python 3
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip3 install -r .github/workflows/requirements/requirements_galaxy.txt

      - name: Import release to Ansible Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
