---
name: Molecule CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Install Ansible core and Ansible Lint
        run: pip3 install -r .github/workflows/requirements/requirements_ansible_lint.txt

      - name: Install Ansible core collection dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml

      - name: Run Ansible Lint
        run: ansible-lint --force-color

  molecule:
    name: Molecule
    runs-on: ubuntu-24.04
    needs: ansible-lint
    env:
      NGINX_CRT: ${{ secrets.NGINX_CRT }}
      NGINX_KEY: ${{ secrets.NGINX_KEY }}
      NGINX_JWT: ${{ secrets.NGINX_JWT }}
      RHEL_USERNAME: ${{ secrets.RHEL_USERNAME }}
      RHEL_PASSWORD: ${{ secrets.RHEL_PASSWORD }}
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - advanced
          - default
          - dos
          - specific-version
          - uninstall
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Install Ansible core and Molecule
        if: ${{ env.NGINX_CRT != 0 && env.NGINX_KEY != 0 }}
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt
        
      - name: Install Ansible core collection dependencies
        if: ${{ env.NGINX_CRT != 0 && env.NGINX_KEY != 0 }}
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml


      - name: Run Molecule tests
        if: ${{ env.NGINX_CRT != 0 && env.NGINX_KEY != 0 }}
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1

