---
name: Molecule CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Ansible Lint
        run: pip3 install -r .github/workflows/requirements/requirements_ansible_lint.txt

      - name: Install Ansible collection dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_ansible.yml

      - name: Run Ansible Lint
        run: ansible-lint --force-color

  molecule:
    name: Molecule
    runs-on: ubuntu-22.04
    needs: ansible-lint
    env:
      NGINX_CRT: ${{ secrets.NGINX_CRT }}
      NGINX_KEY: ${{ secrets.NGINX_KEY }}
      RHEL_USERNAME: ${{ secrets.RHEL_USERNAME }}
      RHEL_PASSWORD: ${{ secrets.RHEL_PASSWORD }}
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - advanced
          - default
          - dos
          - specific-version
          - uninstall
    steps:
      - name: Check out the codebase
        if: ${{ env.NGINX_CRT != 0 && env.NGINX_KEY != 0 }}
        uses: actions/checkout@v4

      - name: Set up Python 3
        if: ${{ env.NGINX_CRT != 0 && env.NGINX_KEY != 0 }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Molecule dependencies
        if: ${{ env.NGINX_CRT != 0 && env.NGINX_KEY != 0 }}
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt

      - name: Install Ansible core dependencies
        if: ${{ env.NGINX_CRT != 0 && env.NGINX_KEY != 0 }}
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_ansible.yml

      - name: Run Molecule tests
        if: ${{ env.NGINX_CRT != 0 && env.NGINX_KEY != 0 }}
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
